name: 01 - Building blocks

on: push

jobs:
    echo-hello:
        runs-on: ubuntu-latest
        steps:
            - name: Say hello
              run: echo "hi baby"
    echo-goodbye:
        runs-on: ubuntu-latest
        steps:
            - name: Sucessful execution
              run: |
                echo "This excecution suceeded"
                exit 0
            - name: Say goodbye
              run: echo "Completed and Goodbye!"    
    
      